name: Test CI

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

# As at 21 June 2023, GitHub hosted runners supply GHC 9.6.2.

jobs:
  test-ci:
    name: Test CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "9.2.7"
        - "9.4.5"
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Install and run
      shell: bash
      run: |
        set -ex

        mkdir -p ~/.stack
        touch ~/.stack/config.yaml
        cat > ~/.stack/config.yaml <<EOF
        extra-include-dirs:
        - /usr/include
        extra-lib-dirs:
        - /lib
        - /usr/lib
        configure-options:
          simple-hsc2hs-test:
          - --hsc2hs-option=--verbose
        EOF

        # Understand the build environment. `stack exec` is one of the
        # subcommands that automatically launches in a Docker container.
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- cat /etc/os-release
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- apk list -I
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- which hsc2hs
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- hsc2hs --version

        stack --verbose --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker build simple-hsc2hs-test --cabal-verbose
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker build hsc2hs-test

        set +ex
  test-th:
    name: Test TH
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
        - "9.2.7"
        - "9.4.5"
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Install and run
      shell: bash
      run: |
        set -ex

        mkdir -p ~/.stack
        touch ~/.stack/config.yaml
        cat > ~/.stack/config.yaml <<EOF
        extra-include-dirs:
        - /usr/include
        extra-lib-dirs:
        - /lib
        - /usr/lib
        EOF

        # Understand the build environment. `stack exec` is one of the
        # subcommands that automatically launches in a Docker container.
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- cat /etc/os-release
        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker exec -- apk list -I

        stack --stack-yaml stack-ghc-${{ matrix.ghc }}.yaml --docker build th-test

        set +ex
